// Core application types

export enum ViewState {
  TOOLS_POS = 'TOOLS_POS',
  DASHBOARD = 'DASHBOARD',
  TOOLS_KITCHEN = 'TOOLS_KITCHEN',
  TOOLS_RECEPTION = 'TOOLS_RECEPTION',
  CLIENT_PORTAL = 'CLIENT_PORTAL',
  SUPER_ADMIN_PORTAL = 'SUPER_ADMIN_PORTAL',
  MANAGEMENT_COST_CONTROL = 'MANAGEMENT_COST_CONTROL',
  MANAGEMENT_AUTOMATION = 'MANAGEMENT_AUTOMATION',
  MANAGEMENT_PROVISIONS = 'MANAGEMENT_PROVISIONS',
  REPORTS_FINANCIAL = 'REPORTS_FINANCIAL',
  REPORTS_TRIAL_BALANCE = 'REPORTS_TRIAL_BALANCE',
  REPORTS_RECONCILIATION = 'REPORTS_RECONCILIATION',
  REPORTS_FIXED_ASSETS = 'REPORTS_FIXED_ASSETS',
  REPORTS_BANK_INSIGHTS = 'REPORTS_BANK_INSIGHTS',
  ANALYTICS_ANOMALY = 'ANALYTICS_ANOMALY',
  ANALYTICS_ADVANCED = 'ANALYTICS_ADVANCED',
  SIMULATION_DASHBOARD = 'SIMULATION_DASHBOARD',
  MANAGEMENT_INVENTORY = 'MANAGEMENT_INVENTORY',
  COMPLIANCE_INTEGRITY = 'COMPLIANCE_INTEGRITY',
  SETTINGS = 'SETTINGS',
  ADMIN_ACCESS_CONTROL = 'ADMIN_ACCESS_CONTROL',
  INDUSTRY_CONSTRUCTION_SITES = 'INDUSTRY_CONSTRUCTION_SITES',
  INDUSTRY_RESTAURANT_TABLES = 'INDUSTRY_RESTAURANT_TABLES',
  INDUSTRY_MEDICAL_PATIENTS = 'INDUSTRY_MEDICAL_PATIENTS',
  INDUSTRY_RETAIL_SHIFTS = 'INDUSTRY_RETAIL_SHIFTS',
  INDUSTRY_TRAVEL_BOOKINGS = 'INDUSTRY_TRAVEL_BOOKINGS',
  INDUSTRY_MAINTENANCE_REQUESTS = 'INDUSTRY_MAINTENANCE_REQUESTS',
  INDUSTRY_REAL_ESTATE_PROPERTIES = 'INDUSTRY_REAL_ESTATE_PROPERTIES',
  INDUSTRY_LEGAL_CASES = 'INDUSTRY_LEGAL_CASES',
  INDUSTRY_LOGISTICS_FLEET = 'INDUSTRY_LOGISTICS_FLEET',
  TOOLS_POS_MANAGEMENT = 'TOOLS_POS_MANAGEMENT',
  HRM_DIRECTORY = 'HRM_DIRECTORY',
  HRM_ATTENDANCE = 'HRM_ATTENDANCE',
  HRM_LEAVE = 'HRM_LEAVE',
  HRM_PAYROLL = 'HRM_PAYROLL',
  HRM_PERFORMANCE = 'HRM_PERFORMANCE',
  INDUSTRY_HOSPITAL_OPERATIONS = 'INDUSTRY_HOSPITAL_OPERATIONS',
  INDUSTRY_CLINIC_SCHEDULER = 'INDUSTRY_CLINIC_SCHEDULER',
  INDUSTRY_PHARMACY_DISPENSARY = 'INDUSTRY_PHARMACY_DISPENSARY',
  INDUSTRY_MANUFACTURING_PRODUCTION = 'INDUSTRY_MANUFACTURING_PRODUCTION',
  INDUSTRY_CRM_PIPELINE = 'INDUSTRY_CRM_PIPELINE',
  INDUSTRY_EDUCATION_CLASSES = 'INDUSTRY_EDUCATION_CLASSES',
  TOOLS_DOCUMENTS = 'TOOLS_DOCUMENTS',
  TOOLS_SALES_INVOICE = 'TOOLS_SALES_INVOICE',
  TOOLS_ZATCA = 'TOOLS_ZATCA',
  TOOLS_IMPORT = 'TOOLS_IMPORT',
  TOOLS_PURCHASING = 'TOOLS_PURCHASING',
  TOOLS_COMMUNICATION = 'TOOLS_COMMUNICATION'
}

export interface Cashier {
  id: string;
  name: string;
  pin: string;
  role?: string;
  isKitchen?: boolean;
}

export type IndustryType = string;
export type UniversalRole = string;
