
export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  
  // Reports
  REPORTS_FINANCIAL = 'REPORTS_FINANCIAL',
  REPORTS_TRIAL_BALANCE = 'REPORTS_TRIAL_BALANCE',
  REPORTS_RECONCILIATION = 'REPORTS_RECONCILIATION',
  REPORTS_FIXED_ASSETS = 'REPORTS_FIXED_ASSETS',
  REPORTS_BANK_INSIGHTS = 'REPORTS_BANK_INSIGHTS',
  
  // Analytics
  ANALYTICS_ANOMALY = 'ANALYTICS_ANOMALY',
  ANALYTICS_ADVANCED = 'ANALYTICS_ADVANCED',
  
  // Simulation & Forecasting
  SIMULATION_DASHBOARD = 'SIMULATION_DASHBOARD',
  
  // Management
  MANAGEMENT_COST_CONTROL = 'MANAGEMENT_COST_CONTROL',
  MANAGEMENT_PROVISIONS = 'MANAGEMENT_PROVISIONS',
  MANAGEMENT_AUTOMATION = 'MANAGEMENT_AUTOMATION',
  MANAGEMENT_INVENTORY = 'MANAGEMENT_INVENTORY',
  
  // Tools
  TOOLS_DOCUMENTS = 'TOOLS_DOCUMENTS',
  TOOLS_SALES_INVOICE = 'TOOLS_SALES_INVOICE',
  TOOLS_ZATCA = 'TOOLS_ZATCA',
  TOOLS_MEETINGS = 'TOOLS_MEETINGS',
  TOOLS_NOTIFICATIONS = 'TOOLS_NOTIFICATIONS',
  TOOLS_POS = 'TOOLS_POS', 
  TOOLS_POS_MANAGEMENT = 'TOOLS_POS_MANAGEMENT',
  TOOLS_IMPORT = 'TOOLS_IMPORT',
  TOOLS_KITCHEN = 'TOOLS_KITCHEN',
  TOOLS_RECEPTION = 'TOOLS_RECEPTION',
  TOOLS_PURCHASING = 'TOOLS_PURCHASING',
  TOOLS_COMMUNICATION = 'TOOLS_COMMUNICATION',
  COMPANY_PORTAL = 'COMPANY_PORTAL',
  ADMIN_ACCESS_CONTROL = 'ADMIN_ACCESS_CONTROL',

  // Industry Specific Views
  INDUSTRY_CONSTRUCTION_SITES = 'INDUSTRY_CONSTRUCTION_SITES',
  INDUSTRY_MEDICAL_PATIENTS = 'INDUSTRY_MEDICAL_PATIENTS',
  INDUSTRY_HOSPITAL_OPERATIONS = 'INDUSTRY_HOSPITAL_OPERATIONS',
  INDUSTRY_CLINIC_SCHEDULER = 'INDUSTRY_CLINIC_SCHEDULER',
  INDUSTRY_RESTAURANT_TABLES = 'INDUSTRY_RESTAURANT_TABLES',
  INDUSTRY_LOGISTICS_FLEET = 'INDUSTRY_LOGISTICS_FLEET',
  INDUSTRY_PHARMACY_DISPENSARY = 'INDUSTRY_PHARMACY_DISPENSARY',
  INDUSTRY_RETAIL_SHIFTS = 'INDUSTRY_RETAIL_SHIFTS',
  INDUSTRY_TRAVEL_BOOKINGS = 'INDUSTRY_TRAVEL_BOOKINGS',
  INDUSTRY_MAINTENANCE_REQUESTS = 'INDUSTRY_MAINTENANCE_REQUESTS',
  INDUSTRY_MANUFACTURING_PRODUCTION = 'INDUSTRY_MANUFACTURING_PRODUCTION',
  INDUSTRY_CRM_PIPELINE = 'INDUSTRY_CRM_PIPELINE',
  INDUSTRY_REAL_ESTATE_PROPERTIES = 'INDUSTRY_REAL_ESTATE_PROPERTIES',
  INDUSTRY_EDUCATION_CLASSES = 'INDUSTRY_EDUCATION_CLASSES',
  INDUSTRY_LEGAL_CASES = 'INDUSTRY_LEGAL_CASES',
  
  // HRM Modules
  HRM_DIRECTORY = 'HRM_DIRECTORY',
  HRM_LEAVE = 'HRM_LEAVE',
  HRM_PAYROLL = 'HRM_PAYROLL',
  HRM_PERFORMANCE = 'HRM_PERFORMANCE',
  HRM_ATTENDANCE = 'HRM_ATTENDANCE',

  // Compliance
  COMPLIANCE_INTEGRITY = 'COMPLIANCE_INTEGRITY',
  
  // System & Admin
  SYSTEM_AUDIT_LOGS = 'SYSTEM_AUDIT_LOGS',
  SUPER_ADMIN_PORTAL = 'SUPER_ADMIN_PORTAL',
  
  // Client Portal
  CLIENT_PORTAL = 'CLIENT_PORTAL',
  
  // Settings
  SETTINGS = 'SETTINGS'
}

export type IndustryType = 
  | 'GENERIC'
  | 'RESTAURANT' 
  | 'CONSTRUCTION' 
  | 'PHARMACY' 
  | 'MEDICAL' 
  | 'HOSPITAL'
  | 'TRAVEL' 
  | 'MAINTENANCE' 
  | 'LOGISTICS' 
  | 'RETAIL'
  | 'MANUFACTURING'
  | 'REAL_ESTATE'
  | 'EDUCATION'
  | 'LEGAL';

export type UniversalRole = 
  | 'OWNER' | 'CEO' | 'GENERAL_MANAGER' | 'BRANCH_MANAGER' | 'DEPARTMENT_MANAGER'
  | 'CHIEF_ACCOUNTANT' | 'ACCOUNTANT' | 'AUDITOR'
  | 'HR_MANAGER' | 'HR_SPECIALIST' | 'RECRUITER'
  | 'WAREHOUSE_MANAGER' | 'STOREKEEPER' | 'INVENTORY_CONTROLLER'
  | 'PURCHASING_MANAGER' | 'PURCHASING_SPECIALIST'
  | 'SALES_MANAGER' | 'SALES_REP' | 'MARKETING_MANAGER' | 'MARKETING_SPECIALIST'
  | 'SYSTEM_ADMIN' | 'IT_SUPPORT' | 'NETWORK_ADMIN'
  | 'RESTAURANT_MANAGER' | 'CASHIER' | 'KITCHEN_STAFF' | 'DELIVERY' | 'RECEPTION' | 'ORDER_COORDINATOR'
  | 'PROJECT_MANAGER' | 'SITE_ENGINEER' | 'CONSTRUCTION_MANAGER' | 'FOREMAN' | 'SAFETY_OFFICER' | 'QUANTITY_SURVEYOR'
  | 'PHARMACIST' | 'PHARMACY_MANAGER' | 'DOCTOR' | 'NURSE' | 'LAB_TECHNICIAN' | 'MEDICAL_REP'
  | 'PLANT_MANAGER' | 'PRODUCTION_LEAD'
  | 'PROPERTY_MANAGER' | 'LEASING_AGENT'
  | 'PRINCIPAL' | 'TEACHER' | 'REGISTRAR'
  | 'PARTNER' | 'LAWYER' | 'PARALEGAL'
  | 'VIEWER' | 'MANAGER' | 'ADMIN'; 

export type AccountType = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
