import React, { useState, useEffect } from 'react';
import { Search, Plus, Edit3, Trash2, Shield, Check, X, Loader2 } from 'lucide-react';
import { AuthService } from '../../services/authService';
import { PortalAdmin, PortalPermissions } from '../../types';
import { SecurityService } from '../../services/securityService';

const DEFAULT_PERMISSIONS: PortalPermissions = {
    manageClients: false,
    suspendAccounts: false,
    viewClientData: true,
    manageAdmins: false,
    resetPasswords: false,
    viewAuditLogs: false,
    manageSupport: true,
    broadcastMessages: false,
    viewAnalytics: true,
    manageSettings: false
};

export const PortalAdminManager: React.FC = () => {
    const [admins, setAdmins] = useState<PortalAdmin[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [currentAdmin, setCurrentAdmin] = useState<Partial<PortalAdmin>>({});

    useEffect(() => {
        loadAdmins();
    }, []);

    const loadAdmins = async () => {
        setIsLoading(true);
        try {
            const adminList = await AuthService.getAdmins();
            setAdmins(adminList);
        } catch (error) {
            console.error("Failed to load admins:", error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!currentAdmin.name || !currentAdmin.email) return;

        if (currentAdmin.id) {
            await AuthService.updateAdmin(currentAdmin as PortalAdmin);
            SecurityService.logAction('ADMIN', 'Super Admin', 'UPDATE', currentAdmin.email, 'Updated Admin Role');
        } else {
            const newAdmin: PortalAdmin = {
                id: '', // Will be generated by service
                name: currentAdmin.name,
                email: currentAdmin.email,
                password: 'tempPassword123', // Default temp pass
                role: 'MANAGER',
                permissions: currentAdmin.permissions || DEFAULT_PERMISSIONS,
                isSetupComplete: false,
                twoFaSecret: undefined
            };
            await AuthService.createAdmin(newAdmin);
            SecurityService.logAction('ADMIN', 'Super Admin', 'CREATE', newAdmin.email, 'Created new Admin');
        }
        await loadAdmins();
        setIsModalOpen(false);
    };

    const handleDelete = async (id: string) => {
        if (window.confirm("Permanently delete this admin?")) {
            await AuthService.deleteAdmin(id);
            SecurityService.logAction('ADMIN', 'Super Admin', 'DELETE', id, 'Deleted Admin');
            await loadAdmins();
        }
    };

    const togglePermission = (key: keyof PortalPermissions) => {
        if (!currentAdmin.permissions) return;
        setCurrentAdmin({
            ...currentAdmin,
            permissions: {
                ...currentAdmin.permissions,
                [key]: !currentAdmin.permissions[key]
            }
        });
    };

    if (isLoading) {
        return (
            <div className="flex items-center justify-center p-12">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
        );
    }

    return (
        <div className="space-y-6 animate-fade-in">
            <div className="flex justify-between items-center">
                <div>
                    <h3 className="font-bold text-on-surface text-lg">System Administrators</h3>
                    <p className="text-sm text-on-surface-muted">Manage access to the Super Admin Portal.</p>
                </div>
                <button 
                    onClick={() => {
                        setCurrentAdmin({ permissions: DEFAULT_PERMISSIONS });
                        setIsModalOpen(true);
                    }}
                    className="px-4 py-2 bg-surface hover:bg-surface-highlight border border-border text-on-surface font-bold rounded-xl flex items-center gap-2 transition"
                >
                    <Plus className="h-4 w-4" /> Add Admin
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
                {admins.map(admin => (
                    <div key={admin.id} className="glass-panel p-6 rounded-2xl border border-border flex flex-col gap-4">
                        <div className="flex justify-between items-start">
                            <div className="flex items-center gap-3">
                                <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-black ${admin.role === 'ROOT' ? 'bg-amber-500' : 'bg-blue-500'}`}>
                                    {admin.name.charAt(0)}
                                </div>
                                <div>
                                    <h4 className="font-bold text-on-surface">{admin.name}</h4>
                                    <span className="text-[10px] font-bold uppercase text-on-surface-muted tracking-wider">{admin.role}</span>
                                </div>
                            </div>
                            {admin.role !== 'ROOT' && (
                                <div className="flex gap-2">
                                    <button onClick={() => { setCurrentAdmin(admin); setIsModalOpen(true); }} className="p-2 hover:bg-surface-highlight rounded-lg text-primary transition"><Edit3 className="h-4 w-4" /></button>
                                    <button onClick={() => handleDelete(admin.id)} className="p-2 hover:bg-surface-highlight rounded-lg text-danger transition"><Trash2 className="h-4 w-4" /></button>
                                </div>
                            )}
                        </div>
                        
                        <div className="text-sm text-on-surface-muted break-all">
                            {admin.email}
                        </div>

                        <div className="mt-auto pt-4 border-t border-border">
                            <p className="text-xs font-bold text-on-surface-muted uppercase mb-2">Permissions</p>
                            <div className="flex flex-wrap gap-2">
                                {Object.entries(admin.permissions).filter(([_, v]) => v).slice(0, 4).map(([k]) => (
                                    <span key={k} className="px-2 py-1 rounded bg-surface-highlight border border-border text-[10px] text-on-surface">
                                        {k.replace(/([A-Z])/g, ' $1').trim()}
                                    </span>
                                ))}
                                {Object.values(admin.permissions).filter(v => v).length > 4 && (
                                    <span className="px-2 py-1 rounded bg-surface-highlight border border-border text-[10px] text-on-surface">+ More</span>
                                )}
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Modal */}
            {isModalOpen && (
                <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[100] flex items-center justify-center p-4 animate-fade-in">
                    <div className="bg-surface border border-border p-8 rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto custom-scrollbar">
                        <h2 className="text-2xl font-bold text-on-surface mb-6">{currentAdmin.id ? 'Edit Admin' : 'New Admin'}</h2>
                        <form onSubmit={handleSave} className="space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                                <div className="space-y-1">
                                    <label className="text-xs font-bold text-on-surface-muted uppercase">Name</label>
                                    <input required type="text" value={currentAdmin.name || ''} onChange={(e) => setCurrentAdmin({...currentAdmin, name: e.target.value})} className="w-full bg-background border border-border rounded-xl px-4 py-2 text-on-surface outline-none focus:border-primary" />
                                </div>
                                <div className="space-y-1">
                                    <label className="text-xs font-bold text-on-surface-muted uppercase">Email</label>
                                    <input required type="email" value={currentAdmin.email || ''} onChange={(e) => setCurrentAdmin({...currentAdmin, email: e.target.value})} className="w-full bg-background border border-border rounded-xl px-4 py-2 text-on-surface outline-none focus:border-primary" />
                                </div>
                            </div>

                            <div>
                                <h4 className="text-sm font-bold text-on-surface mb-3 flex items-center gap-2"><Shield className="h-4 w-4" /> Permissions</h4>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                    {currentAdmin.permissions && Object.keys(DEFAULT_PERMISSIONS).map((key) => (
                                        <div key={key} className="flex items-center justify-between p-3 bg-background border border-border rounded-xl cursor-pointer hover:bg-surface-highlight transition" onClick={() => togglePermission(key as keyof PortalPermissions)}>
                                            <span className="text-sm text-on-surface capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                                            <div className={`w-5 h-5 rounded-full flex items-center justify-center border ${currentAdmin.permissions![key as keyof PortalPermissions] ? 'bg-primary border-primary text-black' : 'border-on-surface-muted'}`}>
                                                {currentAdmin.permissions![key as keyof PortalPermissions] && <Check className="h-3 w-3" />}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            <div className="pt-4 flex gap-3">
                                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 py-3 rounded-xl border border-border font-bold text-on-surface hover:bg-surface-highlight transition">Cancel</button>
                                <button type="submit" className="flex-1 py-3 rounded-xl bg-primary text-black font-bold shadow-glow-primary hover:bg-primary-hover transition">Save Admin</button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};